//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GptEndPoint {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GptEndPoint() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bubba.Properties.GptEndPoint", typeof(GptEndPoint).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/.
        /// </summary>
        internal static string BaseUrl {
            get {
                return ResourceManager.GetString("BaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/files.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/fine_tuning/jobs.
        /// </summary>
        internal static string FineTuning {
            get {
                return ResourceManager.GetString("FineTuning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/images/generations.
        /// </summary>
        internal static string ImageGeneration {
            get {
                return ResourceManager.GetString("ImageGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/organization/projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/audio/speech.
        /// </summary>
        internal static string SpeechGeneration {
            get {
                return ResourceManager.GetString("SpeechGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/chat/completions.
        /// </summary>
        internal static string TextGeneration {
            get {
                return ResourceManager.GetString("TextGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/audio/transcriptions.
        /// </summary>
        internal static string Transcriptions {
            get {
                return ResourceManager.GetString("Transcriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/audio/translations.
        /// </summary>
        internal static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/uploads.
        /// </summary>
        internal static string Uploads {
            get {
                return ResourceManager.GetString("Uploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/embeddings.
        /// </summary>
        internal static string VectorEmbeddings {
            get {
                return ResourceManager.GetString("VectorEmbeddings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.openai.com/v1/vector_stores.
        /// </summary>
        internal static string VectorStores {
            get {
                return ResourceManager.GetString("VectorStores", resourceCulture);
            }
        }
    }
}
