//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bubba.Properties.Locations", typeof(Locations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US,en;q=0.9.
        /// </summary>
        internal static string AcceptLanguage {
            get {
                return ResourceManager.GetString("AcceptLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string ApplicationCache {
            get {
                return ResourceManager.GetString("ApplicationCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\Appropriations\.
        /// </summary>
        internal static string Appropriations {
            get {
                return ResourceManager.GetString("Appropriations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bubba Browser.
        /// </summary>
        internal static string Branding {
            get {
                return ResourceManager.GetString("Branding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\Editor\C.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bubba://UI/Pages/CannotConnect.html.
        /// </summary>
        internal static string CannotConnect {
            get {
                return ResourceManager.GetString("CannotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Google\Chrome\Application\chrome.exe.
        /// </summary>
        internal static string Chrome {
            get {
                return ResourceManager.GetString("Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\CodeEditor\.
        /// </summary>
        internal static string CodeEditor {
            get {
                return ResourceManager.GetString("CodeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\Editor\CPP\.
        /// </summary>
        internal static string CPP {
            get {
                return ResourceManager.GetString("CPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string CrossDomainSecurity {
            get {
                return ResourceManager.GetString("CrossDomainSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\Editor\CS\.
        /// </summary>
        internal static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Stores\.
        /// </summary>
        internal static string DatabaseDirectory {
            get {
                return ResourceManager.GetString("DatabaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\.
        /// </summary>
        internal static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bubba://UI/Pages/Downloads.html.
        /// </summary>
        internal static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe.
        /// </summary>
        internal static string Edge {
            get {
                return ResourceManager.GetString("Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\ExplanatoryStatements\.
        /// </summary>
        internal static string ExplanatoryStatements {
            get {
                return ResourceManager.GetString("ExplanatoryStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bubba://UI/Pages/NotFound.html.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Mozilla Firefox\firefox.exe.
        /// </summary>
        internal static string FireFox {
            get {
                return ResourceManager.GetString("FireFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/.
        /// </summary>
        internal static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file:///C:/Users/terry/source/repos/Bubba/UI/Pages/index.html.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI\Pages\index.html.
        /// </summary>
        internal static string Internal {
            get {
                return ResourceManager.GetString("Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\Editor\JS\.
        /// </summary>
        internal static string JS {
            get {
                return ResourceManager.GetString("JS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Assets\LoaderImages\Loading.gif.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/.
        /// </summary>
        internal static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\terry\source\repos\Bubba\.
        /// </summary>
        internal static string PathPrefix {
            get {
                return ResourceManager.GetString("PathPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.8.8.8.
        /// </summary>
        internal static string PingIP {
            get {
                return ResourceManager.GetString("PingIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.google.com, localhost.
        /// </summary>
        internal static string ProxyBypassList {
            get {
                return ResourceManager.GetString("ProxyBypassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.123.123.123.
        /// </summary>
        internal static string ProxyIP {
            get {
                return ResourceManager.GetString("ProxyIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blaise#2016.
        /// </summary>
        internal static string ProxyPassword {
            get {
                return ResourceManager.GetString("ProxyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string ProxyPort {
            get {
                return ResourceManager.GetString("ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teppler.
        /// </summary>
        internal static string ProxyUsername {
            get {
                return ResourceManager.GetString("ProxyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\Regulations\.
        /// </summary>
        internal static string Regulations {
            get {
                return ResourceManager.GetString("Regulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Reports\Report.xlsx.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cse.google.com/cse?cx=e78aa3dcb21474bf4.
        /// </summary>
        internal static string SearchUrl {
            get {
                return ResourceManager.GetString("SearchUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\Editor\SQL\.
        /// </summary>
        internal static string SQL {
            get {
                return ResourceManager.GetString("SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 /CefSharp Browser.
        /// </summary>
        internal static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Documents\Editor\VBA\.
        /// </summary>
        internal static string VBA {
            get {
                return ResourceManager.GetString("VBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string WebGL {
            get {
                return ResourceManager.GetString("WebGL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string WebSecurity {
            get {
                return ResourceManager.GetString("WebSecurity", resourceCulture);
            }
        }
    }
}
