//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Locations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bubba.Properties.Locations", typeof(Locations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:usace.army.mil .
        /// </summary>
        internal static string ACE {
            get {
                return ResourceManager.GetString("ACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI\Pages\index.html.
        /// </summary>
        internal static string BubbaWeb {
            get {
                return ResourceManager.GetString("BubbaWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.cdc.gov .
        /// </summary>
        internal static string CDC {
            get {
                return ResourceManager.GetString("CDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Google\Chrome\Application\chrome.exe.
        /// </summary>
        internal static string Chrome {
            get {
                return ResourceManager.GetString("Chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:crsreports.congress.gov .
        /// </summary>
        internal static string CRS {
            get {
                return ResourceManager.GetString("CRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.csb.gov .
        /// </summary>
        internal static string CSB {
            get {
                return ResourceManager.GetString("CSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:data.gov .
        /// </summary>
        internal static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Stores\.
        /// </summary>
        internal static string DatabaseDirectory {
            get {
                return ResourceManager.GetString("DatabaseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.dhs.gov .
        /// </summary>
        internal static string DHS {
            get {
                return ResourceManager.GetString("DHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.commerce.gov .
        /// </summary>
        internal static string DOC {
            get {
                return ResourceManager.GetString("DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.defense.gov .
        /// </summary>
        internal static string DOD {
            get {
                return ResourceManager.GetString("DOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.energy.gov .
        /// </summary>
        internal static string DOE {
            get {
                return ResourceManager.GetString("DOE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.doi.gov .
        /// </summary>
        internal static string DOI {
            get {
                return ResourceManager.GetString("DOI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe.
        /// </summary>
        internal static string Edge {
            get {
                return ResourceManager.GetString("Edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;https://www.google.com/search?q=site:www.epa.gov .
        /// </summary>
        internal static string EPA {
            get {
                return ResourceManager.GetString("EPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.fda.gov .
        /// </summary>
        internal static string FDA {
            get {
                return ResourceManager.GetString("FDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Program Files\Mozilla Firefox\firefox.exe.
        /// </summary>
        internal static string FireFox {
            get {
                return ResourceManager.GetString("FireFox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.gpo.gov .
        /// </summary>
        internal static string GPO {
            get {
                return ResourceManager.GetString("GPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.gsa.gov .
        /// </summary>
        internal static string GSA {
            get {
                return ResourceManager.GetString("GSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.hhs.gov .
        /// </summary>
        internal static string HHS {
            get {
                return ResourceManager.GetString("HHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.irs.gov .
        /// </summary>
        internal static string IRS {
            get {
                return ResourceManager.GetString("IRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Assets\LoaderImages\Loading.gif.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:catalog.loc.gov .
        /// </summary>
        internal static string LOC {
            get {
                return ResourceManager.GetString("LOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.archives.gov .
        /// </summary>
        internal static string NARA {
            get {
                return ResourceManager.GetString("NARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.nasa.gov .
        /// </summary>
        internal static string NASA {
            get {
                return ResourceManager.GetString("NASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com.
        /// </summary>
        internal static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.noaa.gov .
        /// </summary>
        internal static string NOAA {
            get {
                return ResourceManager.GetString("NOAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.nps.gov .
        /// </summary>
        internal static string NPS {
            get {
                return ResourceManager.GetString("NPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.nrc.gov .
        /// </summary>
        internal static string NRC {
            get {
                return ResourceManager.GetString("NRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.nsf.gov .
        /// </summary>
        internal static string NSF {
            get {
                return ResourceManager.GetString("NSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.weather.gov .
        /// </summary>
        internal static string NWS {
            get {
                return ResourceManager.GetString("NWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.whitehouse.gov .
        /// </summary>
        internal static string OMB {
            get {
                return ResourceManager.GetString("OMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Users\terry\source\repos\Bubba\.
        /// </summary>
        internal static string PathPrefix {
            get {
                return ResourceManager.GetString("PathPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\Reports\Report.xlsx.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.usda.gov .
        /// </summary>
        internal static string USDA {
            get {
                return ResourceManager.GetString("USDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:www.govinfo.gov .
        /// </summary>
        internal static string USGI {
            get {
                return ResourceManager.GetString("USGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:usno.navy.mil .
        /// </summary>
        internal static string USNO {
            get {
                return ResourceManager.GetString("USNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/search?q=site:fiscal.treasury.gov .
        /// </summary>
        internal static string UST {
            get {
                return ResourceManager.GetString("UST", resourceCulture);
            }
        }
    }
}
