//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bubba.Properties.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to babbage-002.
        /// </summary>
        internal static string babbage_002 {
            get {
                return ResourceManager.GetString("babbage-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft:gpt-4o-2024-08-06:leeroy-jenkins:bro-fine-tuned:BTc3PMb5.
        /// </summary>
        internal static string Bro {
            get {
                return ResourceManager.GetString("Bro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft:gpt-4o-2024-08-06:leeroy-jenkins:bubba-budget-training:BGVjoSXv.
        /// </summary>
        internal static string Bubba {
            get {
                return ResourceManager.GetString("Bubba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chatgpt-4o-latest.
        /// </summary>
        internal static string chatgpt_4o_latest {
            get {
                return ResourceManager.GetString("chatgpt-4o-latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codex-mini-latest.
        /// </summary>
        internal static string codex_mini_latest {
            get {
                return ResourceManager.GetString("codex-mini-latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to computer-use-preview-2025-03-11.
        /// </summary>
        internal static string computer_use_preview {
            get {
                return ResourceManager.GetString("computer-use-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curie-001.
        /// </summary>
        internal static string curie_001 {
            get {
                return ResourceManager.GetString("curie-001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dall-e-2.
        /// </summary>
        internal static string dall_e_2 {
            get {
                return ResourceManager.GetString("dall-e-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dall-e-3.
        /// </summary>
        internal static string dall_e_3 {
            get {
                return ResourceManager.GetString("dall-e-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to davinci-002.
        /// </summary>
        internal static string davinci_002 {
            get {
                return ResourceManager.GetString("davinci-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to davinci-003.
        /// </summary>
        internal static string davinci_003 {
            get {
                return ResourceManager.GetString("davinci-003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-3.5-turbo-0125.
        /// </summary>
        internal static string gpt_3_5_turbo {
            get {
                return ResourceManager.GetString("gpt-3.5-turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-0613.
        /// </summary>
        internal static string gpt_4 {
            get {
                return ResourceManager.GetString("gpt-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4.1-2025-04-14.
        /// </summary>
        internal static string gpt_4_1_ {
            get {
                return ResourceManager.GetString("gpt-4.1 ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4.1-mini-2025-04-14.
        /// </summary>
        internal static string gpt_4_1_mini_ {
            get {
                return ResourceManager.GetString("gpt-4.1-mini ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4.1-nano-2025-04-14.
        /// </summary>
        internal static string gpt_4_1_nano_ {
            get {
                return ResourceManager.GetString("gpt-4.1-nano ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-turbo-2024-04-09.
        /// </summary>
        internal static string gpt_4_turbo {
            get {
                return ResourceManager.GetString("gpt-4-turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-2024-08-06 .
        /// </summary>
        internal static string gpt_4o_ {
            get {
                return ResourceManager.GetString("gpt-4o ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-audio-preview-2024-12-17.
        /// </summary>
        internal static string gpt_4o_audio_preview_ {
            get {
                return ResourceManager.GetString("gpt-4o-audio-preview ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-2024-07-18.
        /// </summary>
        internal static string gpt_4o_mini {
            get {
                return ResourceManager.GetString("gpt-4o-mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-realtime-preview-2024-12-17.
        /// </summary>
        internal static string gpt_4o_mini_realtime_preview {
            get {
                return ResourceManager.GetString("gpt-4o-mini-realtime-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-search-preview-2025-03-1.
        /// </summary>
        internal static string gpt_4o_mini_search_preview {
            get {
                return ResourceManager.GetString("gpt-4o-mini-search-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-transcribe.
        /// </summary>
        internal static string gpt_4o_mini_transcribe {
            get {
                return ResourceManager.GetString("gpt-4o-mini-transcribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-tts.
        /// </summary>
        internal static string gpt_4o_mini_tts {
            get {
                return ResourceManager.GetString("gpt-4o-mini-tts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-realtime-preview-2025-06-03.
        /// </summary>
        internal static string gpt_4o_realtime_preview {
            get {
                return ResourceManager.GetString("gpt-4o-realtime-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-search-preview-2025-03-11.
        /// </summary>
        internal static string gpt_4o_search_preview {
            get {
                return ResourceManager.GetString("gpt-4o-search-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-transcribe.
        /// </summary>
        internal static string gpt_4o_transcribe {
            get {
                return ResourceManager.GetString("gpt-4o-transcribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-image-1.
        /// </summary>
        internal static string gpt_image_1 {
            get {
                return ResourceManager.GetString("gpt-image-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-2024-12-17.
        /// </summary>
        internal static string o1 {
            get {
                return ResourceManager.GetString("o1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-pro-2025-03-19.
        /// </summary>
        internal static string o1_pro {
            get {
                return ResourceManager.GetString("o1-pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o3-2025-04-16.
        /// </summary>
        internal static string o3 {
            get {
                return ResourceManager.GetString("o3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o3-mini-2025-01-31.
        /// </summary>
        internal static string o3_mini {
            get {
                return ResourceManager.GetString("o3-mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o4-mini-2025-04-16.
        /// </summary>
        internal static string o4_mini {
            get {
                return ResourceManager.GetString("o4-mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-embedding-3-large.
        /// </summary>
        internal static string text_embedding_3_large {
            get {
                return ResourceManager.GetString("text-embedding-3-large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-embedding-3-small.
        /// </summary>
        internal static string text_embedding_3_small {
            get {
                return ResourceManager.GetString("text-embedding-3-small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-embedding-ada-002.
        /// </summary>
        internal static string text_embedding_ada_002 {
            get {
                return ResourceManager.GetString("text-embedding-ada-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tts-1.
        /// </summary>
        internal static string tts_1 {
            get {
                return ResourceManager.GetString("tts-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tts-1-hd.
        /// </summary>
        internal static string tts_1_hd {
            get {
                return ResourceManager.GetString("tts-1-hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whisper-1.
        /// </summary>
        internal static string whisper_1 {
            get {
                return ResourceManager.GetString("whisper-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whisper-2.
        /// </summary>
        internal static string whisper_2 {
            get {
                return ResourceManager.GetString("whisper-2", resourceCulture);
            }
        }
    }
}
