//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bubba.Properties.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to babbage-002.
        /// </summary>
        internal static string babbage_002 {
            get {
                return ResourceManager.GetString("babbage-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft:gpt-4o-2024-08-06:leeroy-jenkins:bro-fine-tuned:BTc3PMb5.
        /// </summary>
        internal static string Bro {
            get {
                return ResourceManager.GetString("Bro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ft:gpt-4o-2024-08-06:leeroy-jenkins:bubba-budget-training:BGVjoSXv.
        /// </summary>
        internal static string Bubba {
            get {
                return ResourceManager.GetString("Bubba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chatgpt-4o-latest.
        /// </summary>
        internal static string chatgpt_4o_latest {
            get {
                return ResourceManager.GetString("chatgpt-4o-latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to computer-use-preview-2025-03-11.
        /// </summary>
        internal static string computer_use_preview_2025_03_11 {
            get {
                return ResourceManager.GetString("computer-use-preview-2025-03-11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curie-001.
        /// </summary>
        internal static string curie_001 {
            get {
                return ResourceManager.GetString("curie-001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dall-e-2.
        /// </summary>
        internal static string dall_e_2 {
            get {
                return ResourceManager.GetString("dall-e-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dall-e-3.
        /// </summary>
        internal static string dall_e_3 {
            get {
                return ResourceManager.GetString("dall-e-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to davinci-002.
        /// </summary>
        internal static string davinci_002 {
            get {
                return ResourceManager.GetString("davinci-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to davinci-003.
        /// </summary>
        internal static string davinci_003 {
            get {
                return ResourceManager.GetString("davinci-003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-3.5-turbo.
        /// </summary>
        internal static string gpt_3_5_turbo {
            get {
                return ResourceManager.GetString("gpt-3.5-turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-3.5-turbo-0125.
        /// </summary>
        internal static string gpt_3_5_turbo_0125 {
            get {
                return ResourceManager.GetString("gpt-3.5-turbo-0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4.
        /// </summary>
        internal static string gpt_4 {
            get {
                return ResourceManager.GetString("gpt-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-0125-preview.
        /// </summary>
        internal static string gpt_4_0125_preview {
            get {
                return ResourceManager.GetString("gpt-4-0125-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-0314.
        /// </summary>
        internal static string gpt_4_0314 {
            get {
                return ResourceManager.GetString("gpt-4-0314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-0613.
        /// </summary>
        internal static string gpt_4_0613 {
            get {
                return ResourceManager.GetString("gpt-4-0613", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4.1-2025-04-14.
        /// </summary>
        internal static string gpt_4_1_2025_04_14_ {
            get {
                return ResourceManager.GetString("gpt-4.1-2025-04-14 ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4.1-mini-2025-04-14.
        /// </summary>
        internal static string gpt_4_1_mini_2025_04_14 {
            get {
                return ResourceManager.GetString("gpt-4.1-mini-2025-04-14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-1106-preview.
        /// </summary>
        internal static string gpt_4_1106_preview {
            get {
                return ResourceManager.GetString("gpt-4-1106-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-turbo.
        /// </summary>
        internal static string gpt_4_turbo {
            get {
                return ResourceManager.GetString("gpt-4-turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-turbo-2024-04-09.
        /// </summary>
        internal static string gpt_4_turbo_2024_04_09 {
            get {
                return ResourceManager.GetString("gpt-4-turbo-2024-04-09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-turbo-preview.
        /// </summary>
        internal static string gpt_4_turbo_preview {
            get {
                return ResourceManager.GetString("gpt-4-turbo-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o.
        /// </summary>
        internal static string gpt_4o {
            get {
                return ResourceManager.GetString("gpt-4o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-2024-05-13.
        /// </summary>
        internal static string gpt_4o_2024_05_13 {
            get {
                return ResourceManager.GetString("gpt-4o-2024-05-13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-2024-08-06 .
        /// </summary>
        internal static string gpt_4o_2024_08_06 {
            get {
                return ResourceManager.GetString("gpt-4o-2024-08-06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPT-4o-2024-11-20 .
        /// </summary>
        internal static string gpt_4o_2024_11_20 {
            get {
                return ResourceManager.GetString("gpt-4o-2024-11-20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-audio-preview .
        /// </summary>
        internal static string gpt_4o_audio_preview {
            get {
                return ResourceManager.GetString("gpt-4o-audio-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-audio-preview-2024-10-01.
        /// </summary>
        internal static string gpt_4o_audio_preview_2024_10_01 {
            get {
                return ResourceManager.GetString("gpt-4o-audio-preview-2024-10-01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-audio-preview-2024-12-17.
        /// </summary>
        internal static string gpt_4o_audio_preview_2024_12_17 {
            get {
                return ResourceManager.GetString("gpt-4o-audio-preview-2024-12-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini.
        /// </summary>
        internal static string gpt_4o_mini {
            get {
                return ResourceManager.GetString("gpt-4o-mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-2024-07-18.
        /// </summary>
        internal static string gpt_4o_mini_2024_07_18 {
            get {
                return ResourceManager.GetString("gpt-4o-mini-2024-07-18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-realtime-preview.
        /// </summary>
        internal static string gpt_4o_mini_realtime_preview {
            get {
                return ResourceManager.GetString("gpt-4o-mini-realtime-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-realtime-preview-2024-12-17.
        /// </summary>
        internal static string gpt_4o_mini_realtime_preview_2024_12_17 {
            get {
                return ResourceManager.GetString("gpt-4o-mini-realtime-preview-2024-12-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-search-preview-2025-03-1.
        /// </summary>
        internal static string gpt_4o_mini_search_preview_2025_03_11 {
            get {
                return ResourceManager.GetString("gpt-4o-mini-search-preview-2025-03-11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-realtime-preview.
        /// </summary>
        internal static string gpt_4o_realtime_preview {
            get {
                return ResourceManager.GetString("gpt-4o-realtime-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-realtime-preview-2024-10-01.
        /// </summary>
        internal static string gpt_4o_realtime_preview_2024_10_01 {
            get {
                return ResourceManager.GetString("gpt-4o-realtime-preview-2024-10-01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-realtime-preview-2024-12-17.
        /// </summary>
        internal static string gpt_4o_realtime_preview_2024_12_17 {
            get {
                return ResourceManager.GetString("gpt-4o-realtime-preview-2024-12-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-search-preview-2025-03-11.
        /// </summary>
        internal static string gpt_4o_search_preview_2025_03_11 {
            get {
                return ResourceManager.GetString("gpt-4o-search-preview-2025-03-11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1.
        /// </summary>
        internal static string o1 {
            get {
                return ResourceManager.GetString("o1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-2024-12-17.
        /// </summary>
        internal static string o1_2024_12_17 {
            get {
                return ResourceManager.GetString("o1-2024-12-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-mini.
        /// </summary>
        internal static string o1_mini {
            get {
                return ResourceManager.GetString("o1-mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-mini-2024-09-12.
        /// </summary>
        internal static string o1_mini_2024_09_12 {
            get {
                return ResourceManager.GetString("o1-mini-2024-09-12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-preview.
        /// </summary>
        internal static string o1_preview {
            get {
                return ResourceManager.GetString("o1-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-preview-2024-09-12.
        /// </summary>
        internal static string o1_preview_2024_09_12 {
            get {
                return ResourceManager.GetString("o1-preview-2024-09-12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-pro-2025-03-19.
        /// </summary>
        internal static string o1_pro_2025_03_19 {
            get {
                return ResourceManager.GetString("o1-pro-2025-03-19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o3-2025-04-16.
        /// </summary>
        internal static string o3_2025_04_16 {
            get {
                return ResourceManager.GetString("o3-2025-04-16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o3-mini.
        /// </summary>
        internal static string o3_mini {
            get {
                return ResourceManager.GetString("o3-mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o4-mini-2025-04-16.
        /// </summary>
        internal static string o4_mini_2025_04_16 {
            get {
                return ResourceManager.GetString("o4-mini-2025-04-16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-embedding-3-large.
        /// </summary>
        internal static string text_embedding_3_large {
            get {
                return ResourceManager.GetString("text-embedding-3-large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-embedding-3-small.
        /// </summary>
        internal static string text_embedding_3_small {
            get {
                return ResourceManager.GetString("text-embedding-3-small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-embedding-ada-002.
        /// </summary>
        internal static string text_embedding_ada_002 {
            get {
                return ResourceManager.GetString("text-embedding-ada-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tts-1.
        /// </summary>
        internal static string tts_1 {
            get {
                return ResourceManager.GetString("tts-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tts-1-hd.
        /// </summary>
        internal static string tts_1_hd {
            get {
                return ResourceManager.GetString("tts-1-hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whisper-1.
        /// </summary>
        internal static string whisper_1 {
            get {
                return ResourceManager.GetString("whisper-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whisper-2.
        /// </summary>
        internal static string whisper_2 {
            get {
                return ResourceManager.GetString("whisper-2", resourceCulture);
            }
        }
    }
}
