//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubba.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bubba.Properties.Models", typeof(Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to babbage-002Replacement for the GPT-3 ada and babbage base models. GPT base models can understand and generate natural language or code but are not trained with instruction following. These models are made to be replacements for the original GPT-3 base models and use the legacy Completions API. .
        /// </summary>
        internal static string babbage_002 {
            get {
                return ResourceManager.GetString("babbage-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model continuously points to the version of GPT-4o used in ChatGPT. It is updated frequently, when there are significant changes to ChatGPT&apos;s GPT-4o model. The knowledge cutoff for GPT-4o models is October, 2023..
        /// </summary>
        internal static string chatgpt_4o_latest {
            get {
                return ResourceManager.GetString("chatgpt-4o-latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curie-001;  GPT base models can understand and generate natural language or code but are not trained with instruction following. These models are made to be replacements for the original GPT-3 base models and use the legacy Completions API. .
        /// </summary>
        internal static string curie_001 {
            get {
                return ResourceManager.GetString("curie-001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dall-e-2;  DALL·E is a AI system that can create realistic images and art from a description in natural language. DALL·E 3 currently supports the ability, given a prompt, to create a new image with a specific size. DALL·E 2 also support the ability to edit an existing image, or create variations of a user provided image.   .
        /// </summary>
        internal static string dall_e_2 {
            get {
                return ResourceManager.GetString("dall-e-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dall-e-3;  DALL·E is a AI system that can create realistic images and art from a description in natural language. DALL·E 3 currently supports the ability, given a prompt, to create a new image with a specific size. DALL·E 2 also support the ability to edit an existing image, or create variations of a user provided image..
        /// </summary>
        internal static string dall_e_3 {
            get {
                return ResourceManager.GetString("dall-e-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to davinci-002;  GPT base models can understand and generate natural language or code but are not trained with instruction following. These models are made to be replacements for the original GPT-3 base models and use the legacy Completions API. .
        /// </summary>
        internal static string davinci_002 {
            get {
                return ResourceManager.GetString("davinci-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to davinci-003;  GPT base models can understand and generate natural language or code but are not trained with instruction following. These models are made to be replacements for the original GPT-3 base models and use the legacy Completions API. .
        /// </summary>
        internal static string davinci_003 {
            get {
                return ResourceManager.GetString("davinci-003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-3.5-turbo; Currently points to gpt-3.5-turbo-0125..
        /// </summary>
        internal static string gpt_3_5_turbo {
            get {
                return ResourceManager.GetString("gpt-3.5-turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-3.5-turbo-0125; GPT-3.5 Turbo models can understand and generate natural language or code and have been optimized for chat using the Chat Completions API but work well for non-chat tasks as well..
        /// </summary>
        internal static string gpt_3_5_turbo_0125 {
            get {
                return ResourceManager.GetString("gpt-3.5-turbo-0125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;  GPT-4 is an older version of a high-intelligence GPT model, usable in Chat Completions. .
        /// </summary>
        internal static string gpt_4 {
            get {
                return ResourceManager.GetString("gpt-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-0125-preview;  GPT-4 is an older version of a high-intelligence GPT model, usable in Chat Completions. .
        /// </summary>
        internal static string gpt_4_0125_preview {
            get {
                return ResourceManager.GetString("gpt-4-0125-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-0314;  GPT-4 is an older version of a high-intelligence GPT model, usable in Chat Completions. .
        /// </summary>
        internal static string gpt_4_0314 {
            get {
                return ResourceManager.GetString("gpt-4-0314", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4 is an older version of a high-intelligence GPT model, usable in Chat Completions. .
        /// </summary>
        internal static string gpt_4_0613 {
            get {
                return ResourceManager.GetString("gpt-4-0613", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-1106-preview; GPT-4 is an older version of a high-intelligence GPT model, usable in Chat Completions. .
        /// </summary>
        internal static string gpt_4_1106_preview {
            get {
                return ResourceManager.GetString("gpt-4-1106-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-turbo;  GPT-4 is an older version of a high-intelligence GPT model, usable in Chat Completions. Image inputs via the o1, gpt-4o, gpt-4o-mini, chatgpt-4o-latest, or gpt-4-turbo models (or previously gpt-4-vision-preview) are not eligible for zero retention..
        /// </summary>
        internal static string gpt_4_turbo {
            get {
                return ResourceManager.GetString("gpt-4-turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-turbo-2024-04-09.  GPT-4 is an older version of a high-intelligence GPT model, usable in Chat Completions. Image inputs via the o1, gpt-4o, gpt-4o-mini, chatgpt-4o-latest, or gpt-4-turbo models (or previously gpt-4-vision-preview) are not eligible for zero retention..
        /// </summary>
        internal static string gpt_4_turbo_2024_04_09 {
            get {
                return ResourceManager.GetString("gpt-4-turbo-2024-04-09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4-turbo-preview;  GPT-4 is an older version of a high-intelligence GPT model, usable in Chat Completions. Image inputs via the o1, gpt-4o, gpt-4o-mini, chatgpt-4o-latest, or gpt-4-turbo models (or previously gpt-4-vision-preview) are not eligible for zero retention..
        /// </summary>
        internal static string gpt_4_turbo_preview {
            get {
                return ResourceManager.GetString("gpt-4-turbo-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o (“o” for “omni”) a versatile, high-intelligence flagship model. It accepts both text and image inputs, and produces text outputs (including Structured Outputs).  Image inputs via the o1, gpt-4o, gpt-4o-mini, chatgpt-4o-latest, or gpt-4-turbo models (or previously gpt-4-vision-preview) are not eligible for zero retention..
        /// </summary>
        internal static string gpt_4o {
            get {
                return ResourceManager.GetString("gpt-4o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-2024-05-13 (“o” for “omni”) a versatile, high-intelligence flagship model. It accepts both text and image inputs, and produces text outputs (including Structured Outputs).  Image inputs via the o1, gpt-4o, gpt-4o-mini, chatgpt-4o-latest, or gpt-4-turbo models (or previously gpt-4-vision-preview) are not eligible for zero retention..
        /// </summary>
        internal static string gpt_4o_2024_05_13 {
            get {
                return ResourceManager.GetString("gpt-4o-2024-05-13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-2024-08-06 (“o” for “omni”) a versatile, high-intelligence flagship model. It accepts both text and image inputs, and produces text outputs (including Structured Outputs). Image inputs via the o1, gpt-4o, gpt-4o-mini, chatgpt-4o-latest, or gpt-4-turbo models (or previously gpt-4-vision-preview) are not eligible for zero retention..
        /// </summary>
        internal static string gpt_4o_2024_08_06 {
            get {
                return ResourceManager.GetString("gpt-4o-2024-08-06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPT-4o-2024-11-20 (“o” for “omni”) is a versatile, high-intelligence flagship model. It accepts both text and image inputs, and produces text outputs (including Structured Outputs). Image inputs via the o1, gpt-4o, gpt-4o-mini, chatgpt-4o-latest, or gpt-4-turbo models (or previously gpt-4-vision-preview) are not eligible for zero retention..
        /// </summary>
        internal static string gpt_4o_2024_11_20 {
            get {
                return ResourceManager.GetString("gpt-4o-2024-11-20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-audio-preview; These models accept audio inputs and outputs, and can be used in the Chat Completions REST API..
        /// </summary>
        internal static string gpt_4o_audio_preview {
            get {
                return ResourceManager.GetString("gpt-4o-audio-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-audio-preview-2024-10-01;  These models accept audio inputs and outputs, and can be used in the Chat Completions REST API.
        /// </summary>
        internal static string gpt_4o_audio_preview_2024_10_01 {
            get {
                return ResourceManager.GetString("gpt-4o-audio-preview-2024-10-01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-audio-preview-2024-12-17;  These models accept audio inputs and outputs, and can be used in the Chat Completions REST API..
        /// </summary>
        internal static string gpt_4o_audio_preview_2024_12_17 {
            get {
                return ResourceManager.GetString("gpt-4o-audio-preview-2024-12-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini (“o” for “omni”) is a versatile, high-intelligence flagship model. It accepts both text and image inputs, and produces text outputs (including Structured Outputs). Image inputs via the o1, gpt-4o, gpt-4o-mini, chatgpt-4o-latest, or gpt-4-turbo models (or previously gpt-4-vision-preview) are not eligible for zero retention..
        /// </summary>
        internal static string gpt_4o_mini {
            get {
                return ResourceManager.GetString("gpt-4o-mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-2024-07-18 (“o” for “omni”) is a versatile, high-intelligence flagship model. It accepts both text and image inputs, and produces text outputs (including Structured Outputs). Image inputs via the o1, gpt-4o, gpt-4o-mini, chatgpt-4o-latest, or gpt-4-turbo models (or previously gpt-4-vision-preview) are not eligible for zero retention..
        /// </summary>
        internal static string gpt_4o_mini_2024_07_18 {
            get {
                return ResourceManager.GetString("gpt-4o-mini-2024-07-18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-realtime-preview;  These models are capable of responding to audio and text inputs in realtime over WebRTC or a WebSocket interface. The knowledge cutoff for GPT-4o Realtime models is October, 2023..
        /// </summary>
        internal static string gpt_4o_mini_realtime_preview {
            get {
                return ResourceManager.GetString("gpt-4o-mini-realtime-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-mini-realtime-preview-2024-12-17;  These models are capable of responding to audio and text inputs in realtime over WebRTC or a WebSocket interface. The knowledge cutoff for GPT-4o Realtime models is October, 2023..
        /// </summary>
        internal static string gpt_4o_mini_realtime_preview_2024_12_17 {
            get {
                return ResourceManager.GetString("gpt-4o-mini-realtime-preview-2024-12-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-realtime-preview;   These models are capable of responding to audio and text inputs in realtime over WebRTC or a WebSocket interface. The knowledge cutoff for GPT-4o Realtime models is October, 2023..
        /// </summary>
        internal static string gpt_4o_realtime_preview {
            get {
                return ResourceManager.GetString("gpt-4o-realtime-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-realtime-preview-2024-10-01;  These models are capable of responding to audio and text inputs in realtime over WebRTC or a WebSocket interface. The knowledge cutoff for GPT-4o Realtime models is October, 2023..
        /// </summary>
        internal static string gpt_4o_realtime_preview_2024_10_01 {
            get {
                return ResourceManager.GetString("gpt-4o-realtime-preview-2024-10-01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gpt-4o-realtime-preview-2024-12-17;  These models are capable of responding to audio and text inputs in realtime over WebRTC or a WebSocket interface. The knowledge cutoff for GPT-4o Realtime models is October, 2023..
        /// </summary>
        internal static string gpt_4o_realtime_preview_2024_12_17 {
            get {
                return ResourceManager.GetString("gpt-4o-realtime-preview-2024-12-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The o1 series of models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought before responding to the user. .
        /// </summary>
        internal static string o1 {
            get {
                return ResourceManager.GetString("o1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The o1 series of models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought. o1: reasoning model designed to solve hard problems across domains user..
        /// </summary>
        internal static string o1_2024_12_17 {
            get {
                return ResourceManager.GetString("o1-2024-12-17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The o1 series of models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought before responding to the user..
        /// </summary>
        internal static string o1_mini {
            get {
                return ResourceManager.GetString("o1-mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-mini-2024-09-12; The o1 series of models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought before responding to the user..
        /// </summary>
        internal static string o1_mini_2024_09_12 {
            get {
                return ResourceManager.GetString("o1-mini-2024-09-12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-preview;  The o1 series of models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought before responding to the user..
        /// </summary>
        internal static string o1_preview {
            get {
                return ResourceManager.GetString("o1-preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o1-preview-2024-09-12;  The o1 series of models are trained with reinforcement learning to perform complex reasoning. o1 models think before they answer, producing a long internal chain of thought before responding to the user..
        /// </summary>
        internal static string o1_preview_2024_09_12 {
            get {
                return ResourceManager.GetString("o1-preview-2024-09-12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-embedding-3-large;  Embeddings are a numerical representation of text that can be used to measure the relatedness between two pieces of text. Embeddings are useful for search, clustering, recommendations, anomaly detection, and classification tasks.
        /// </summary>
        internal static string text_embedding_3_large {
            get {
                return ResourceManager.GetString("text-embedding-3-large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-embedding-3-small;  Embeddings are a numerical representation of text that can be used to measure the relatedness between two pieces of text. Embeddings are useful for search, clustering, recommendations, anomaly detection, and classification tasks..
        /// </summary>
        internal static string text_embedding_3_small {
            get {
                return ResourceManager.GetString("text-embedding-3-small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-embedding-ada-002; Embeddings are a numerical representation of text that can be used to measure the relatedness between two pieces of text. Embeddings are useful for search, clustering, recommendations, anomaly detection, and classification tasks..
        /// </summary>
        internal static string text_embedding_ada_002 {
            get {
                return ResourceManager.GetString("text-embedding-ada-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tts-1;  TTS is an AI model that converts text to natural sounding spoken text. We offer two different model variates, tts-1 is optimized for real time text to speech use cases and tts-1-hd is optimized for quality. These models can be used with the Speech endpoint in the Audio API. Audio outputs are stored for 1 hour to enable multi-turn conversations, and are not currently eligible for zero retention..
        /// </summary>
        internal static string tts_1 {
            get {
                return ResourceManager.GetString("tts-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tts-1-hd; TTS is an AI model that converts text to natural sounding spoken text. We offer two different model variates, tts-1 is optimized for real time text to speech use cases and tts-1-hd is optimized for quality. These models can be used with the Speech endpoint in the Audio API. Audio outputs are stored for 1 hour to enable multi-turn conversations, and are not currently eligible for zero retention..
        /// </summary>
        internal static string tts_1_hd {
            get {
                return ResourceManager.GetString("tts-1-hd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whisper is a general-purpose speech recognition model. It is trained on a large dataset of diverse audio and is also a multi-task model that can perform multilingual speech recognition as well as speech translation and language identification. The Whisper v2-large model is currently available through our API with the whisper-1 model name. Audio outputs are stored for 1 hour to enable multi-turn conversations, and are not currently eligible for zero retention..
        /// </summary>
        internal static string whisper_1 {
            get {
                return ResourceManager.GetString("whisper-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to whisper-2;  Whisper is a general-purpose speech recognition model. It is trained on a large dataset of diverse audio and is also a multi-task model that can perform multilingual speech recognition as well as speech translation and language identification. The Whisper v2-large model is currently available through our API with the whisper-1 model name. Audio outputs are stored for 1 hour to enable multi-turn conversations, and are not currently eligible for zero retention..
        /// </summary>
        internal static string whisper_2 {
            get {
                return ResourceManager.GetString("whisper-2", resourceCulture);
            }
        }
    }
}
